name: Issue Close Require

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  close-issues:
    runs-on: ubuntu-latest
    steps:
      - name: need reproduction
        uses: actions-cool/issues-helper@0a220d0ec9d2711f3a181d7e332be32013e68ac8
        with:
          actions: close-issues
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: need reproduction
          inactive-day: 3
